In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
# WARNING, FILE "delay_clean.csv" is 2.5 GB  --  added to gitignore

clean_data = pd.read_csv("./delay_clean.csv", encoding = 'utf-8')
clean = pd.DataFrame(clean_data)

## Random Forest Model

In [3]:
clean.sample(10)

,DEP_DEL15,MONTH_1,MONTH_10,MONTH_11,MONTH_12,MONTH_2,MONTH_3,MONTH_4,MONTH_5,MONTH_6,...,"PRCP_groups_(0.07, 11.63]","SNOW_groups_(-0.001, 17.2]","TMAX_groups_(-10.001, 59.0]","TMAX_groups_(59.0, 74.0]","TMAX_groups_(74.0, 86.0]","TMAX_groups_(86.0, 115.0]","AWND_groups_(-0.001, 5.82]","AWND_groups_(5.82, 7.83]","AWND_groups_(7.83, 10.29]","AWND_groups_(10.29, 33.78]"
5097327,0,0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,1,0,0,0
3456151,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,1,0,0,0
1017407,1,0,0,0,0,0,1,0,0,0,...,0,1,0,0,1,0,0,0,0,1
587826,1,0,0,0,0,1,0,0,0,0,...,1,1,0,1,0,0,1,0,0,0
3415129,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,0,0,1,0
1387426,0,0,0,0,0,0,1,0,0,0,...,0,1,1,0,0,0,0,0,0,1
4206049,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
4879265,0,0,1,0,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,0
5463980,0,0,0,1,0,0,0,0,0,0,...,0,1,0,1,0,0,1,0,0,0
3559194,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,0

In [4]:
# Remove "DEP_DEL15" target (delayed more than 15 minutes) from features data

y = clean.DEP_DEL15
X = clean.drop("DEP_DEL15", axis = 1)

In [5]:
# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 50, stratify = y)

In [6]:
# Create a StandardScaler instance
scaler = StandardScaler()

In [7]:
# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

In [8]:
# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators = 128, random_state = 50)

In [ ]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [ ]:
# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")